### ISSUE TITLE
Stream closed exception in logs

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-mysql-maven-plugin#30]
When plugin shuts down, this is what I see in logs:

```
[WARNING] escalated exception: java.lang.IllegalArgumentException: java.io.IOException: Stream closed
    at com.jcabi.log.VerboseRunnable$1.run(VerboseRunnable.java:142)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:201)
    at java.lang.Thread.run(Thread.java:701)
Caused by: java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:282)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:324)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:176)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:153)
    at java.io.BufferedReader.readLine(BufferedReader.java:316)
    at java.io.BufferedReader.readLine(BufferedReader.java:379)
    at com.jcabi.log.VerboseProcess$1.call(VerboseProcess.java:260)
    at com.jcabi.log.VerboseProcess$1.call(VerboseProcess.java:249)
    at com.jcabi.log.VerboseRunnable$1.run(VerboseRunnable.java:139)
    ... 2 more
```

Doesn't affect anything, but is rather annoying. Would be great to fix.

**Comment by longtimeago** [comment]
@yegor256 ping :)

**Comment by yegor256** [comment]
@longtimeago let me check...

**Comment by longtimeago** [comment]
@yegor256 ping :)

**Comment by longtimeago** [comment]
@yegor256 Any news here?

**Comment by longtimeago** [comment]
@yegor256 need your attention here. Closed month ago but still in the list of tasks on netbout

**Comment by yegor256** [comment]
@longtimeago it'll be closed/paid tomorrow the latest. there were some issues, resolved them already

**Comment by longtimeago** [comment]
@yegor256 great, thanks!

**Comment by dmarkov** [comment]
@longtimeago **30 mins** added to your account (payment number `50616319`), many thanks for your contribution!... +30 added to your rating, at the moment it is: [+1367](http://www.netbout.com/b/35024?open=rating)
