### ISSUE TITLE
Need support for basic usage of jcabi

### ISSUE THREAD

**Issue by jsebfranck** [jcabi/jcabi-mysql-maven-plugin#71]
Hi,

I'm trying to use Jcabi for the first time.

I have created a simple maven project from the example I found here : http://www.yegor256.com/2014/05/21/mysql-maven-plugin.html.

My sources are here : https://github.com/jsebfranck/jcabi-proto

When I launch "mvn install", the build fails with the following output :

```
D:\java\projects\workspace\protojcabi>mvn install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
com.jsebfranck:protojcabi:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-fail
safe-plugin is missing. @ line 76, column 12
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-mave
n-plugin is missing. @ line 19, column 12
[WARNING] 'build.plugins.plugin.version' for com.jcabi:jcabi-mysql-maven-plugin
is missing. @ line 58, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO]
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethrea
ded.SingleThreadedBuilder with a thread count of 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building protojcabi 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- jcabi-mysql-maven-plugin:0.9:classify (mysql-test) @ protojcabi ---
[INFO] ${mysql.classifier} set to "windows-amd64"
[INFO]
[INFO] --- maven-dependency-plugin:2.8:unpack (default) @ protojcabi ---
[INFO] Configured Artifact: com.jcabi:mysql-dist:windows-amd64:5.6.14:zip
[INFO] mysql-dist-5.6.14-windows-amd64.zip already unpacked.
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ protojcabi
 ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ protojcabi --
-
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ pr
otojcabi ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,
i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ proto
jcabi ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- build-helper-maven-plugin:1.9.1:reserve-network-port (default) @ prot
ojcabi ---
[INFO] Reserved port 54597 for mysql.port
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ protojcabi ---
[INFO] Surefire report directory: D:\java\projects\workspace\protojcabi\target\s
urefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.jsebfranck.jcabi.MysqlTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.161 sec <<< FA
ILURE!
worksWithMysqlServer(com.jsebfranck.jcabi.MysqlTest)  Time elapsed: 0.052 sec  <
<< ERROR!
java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:null/
root?user=root&password=root
        at java.sql.DriverManager.getConnection(DriverManager.java:596)
        at java.sql.DriverManager.getConnection(DriverManager.java:233)
        at com.jsebfranck.jcabi.MysqlTest.worksWithMysqlServer(MysqlTest.java:15
)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
Method.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
lable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
thod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
hod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(
ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke
(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(Provi
derFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
75)


Results :

Tests in error:
  worksWithMysqlServer(com.jsebfranck.jcabi.MysqlTest): No suitable driver found
 for jdbc:mysql://localhost:null/root?user=root&password=root

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.196 s
[INFO] Finished at: 2015-04-16T09:47:20+01:00
[INFO] Final Memory: 18M/227M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
12.4:test (default-test) on project protojcabi: There are test failures.
[ERROR]
[ERROR] Please refer to D:\java\projects\workspace\protojcabi\target\surefire-re
ports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
```

Seems that the mysql database is not launched before the tests and that the port is not injected within the test. Maybe it is because my test is not marked as an integration test ?

Please note that when I launch "mvn mysql-jabi:run", it seems to work correctly.

Any idea to resolve this problem ?

Thanks.

**Comment by mike10004** [comment]
What if you include the MySQL driver as a dependency in pom.xml?

That is, add 

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.35</version>
            <scope>runtime</scope>
        </dependency>

in the `<dependencies>` section of `pom.xml`.

**Comment by yegor256** [comment]
@jsebfranck yes, @mike10004 is right, you should add this dependency to your pom

**Comment by jsebfranck** [comment]
Still not working with the same error... it seems that my tests are executed before mysql starts... However, if I skip my tests (-DskipTests), Mysql is correctly launched. Should I do something specific to mark my tests as integration tests ?

**Comment by mike10004** [comment]
Are you sure you're getting the same error? When I build, the error is a NumberFormatException because the `mysql.port` system property is not yet set.

The surefire plugin runs tests that are named xyzTest, and the failsafe plugin runs tests named xyzIT. Your test is MysqlTest, so surefire tries to run it, but the system property defining the MySQL port is only available during failsafe's execution, so the value is null.

A few other things:

* the database name to use is `test` instead of `root`. 
* specify `mysql-dist` artifact version 5.5.34 instead of 5.6.14; see https://github.com/jcabi/jcabi-mysql-maven-plugin/issues/57 for discussion
* there's some other problem with newer versions of the plugin on Windows; downgrade `jcabi-mysql-maven-plugin` to version 0.7; see https://github.com/jcabi/jcabi-mysql-maven-plugin/issues/56

See https://github.com/jsebfranck/jcabi-proto/compare/master...mike10004:master

**Comment by jsebfranck** [comment]
Thanks you so much, it works now in my console. Next step for me will be to use your plugin directly in eclipse. It would be great if I could use it directly with Junit (Run as > junit tests) but it doesn't work for the moment.

**Comment by JESShEart** [comment]
I run the tests from within my IDE by doing the following:
Run this maven command to get the jcabi MySQLrunning
```
mvn jcabi-mysql:run
```
When running that command, It always runs the MySQL server on port 3306
In my test I get the port number like this:
```
String port = System.getProperty("mysql.port");
port = port==null ? "3306" : port;
```
So, if the system property is not set, it fall back to using 3306.
Now, as long as that MySQL server is up an running, you should be able to run your tests from your IDE.
