### ISSUE TITLE
Failed to build jcabi-mysql-maven-plugin

### ISSUE THREAD

**Issue by tmjee** [jcabi/jcabi-mysql-maven-plugin#78]
Can't build using
```
 mvn clean install -Pqulice
```

got lots of the following exception 
```
[INFO] [ERROR] Failed to execute goal com.jcabi:jcabi-mysql-maven-plugin:1.0-SNAPSHOT:start (start-stop-first) on project parallel: failed to start MySQL server: socket /home/tmjee/private/repos/jcabi/jcabi-mysql-maven-plugin/target/it/parallel/target/mysql-data-first/mysql.sock is not available after 5min of waiting -> [Help 1]
[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.jcabi:jcabi-mysql-maven-plugin:1.0-SNAPSHOT:start (start-stop-first) on project parallel: failed to start MySQL server
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[INFO]  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[INFO]  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[INFO]  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[INFO]  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[INFO]  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
[INFO]  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
[INFO]  at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:606)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Caused by: org.apache.maven.plugin.MojoFailureException: failed to start MySQL server
[INFO]  at com.jcabi.mysql.maven.plugin.StartMojo.run(StartMojo.java:64)
[INFO]  at com.jcabi.mysql.maven.plugin.AbstractMysqlMojo.execute(AbstractMysqlMojo.java:174)
[INFO]  at com.jcabi.mysql.maven.plugin.StartMojo.execute(StartMojo.java:45)
[INFO]  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[INFO]  ... 20 more 
[INFO] Caused by: java.io.IOException: socket /home/tmjee/private/repos/jcabi/jcabi-mysql-maven-plugin/target/it/parallel/target/mysql-data-first/mysql.sock is not available after 5min of waiting
[INFO]  at com.jcabi.mysql.maven.plugin.Instances.waitFor(Instances.java:327)
[INFO]  at com.jcabi.mysql.maven.plugin.Instances.process(Instances.java:232)
[INFO]  at com.jcabi.mysql.maven.plugin.Instances.start_aroundBody0(Instances.java:135)
[INFO]  at com.jcabi.mysql.maven.plugin.Instances$AjcClosure1.run(Instances.java:1)
[INFO]  at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
[INFO]  at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
[INFO]  at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
[INFO]  at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
[INFO]  at com.jcabi.mysql.maven.plugin.Instances.start(Instances.java:128)
[INFO]  at com.jcabi.mysql.maven.plugin.StartMojo.run(StartMojo.java:56)
[INFO]  ... 24 more

```

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by jrdalpra** [comment]
@yegor256 the project is unstable as you can see here http://www.rultor.com/p/jcabi/jcabi-mysql-maven-plugin, here https://travis-ci.org/jcabi/jcabi-mysql-maven-plugin and here https://ci.appveyor.com/project/yegor256/jcabi-mysql-maven-plugin
And it's also blocking me to solve this issue #58 

Can you solve, please?

**Comment by yegor256** [comment]
@jrdalpra hm... looking into it

**Comment by jrdalpra** [comment]
@yegor256 it was solved? I have a task waiting this one. Thanks.
