### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by MHL3060** [jcabi/jcabi-mysql-maven-plugin#88]
Hi I am seeing this when the build finished. 

mvn -version

```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T12:39:06-07:00)
Maven home: /opt/apache-maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.4", arch: "x86_64", family: "mac"

```

```
Exception in thread "Thread-14" java.lang.NoClassDefFoundError: com/jcabi/mysql/maven/plugin/Instances$AjcClosure3
	at com.jcabi.mysql.maven.plugin.Instances.stop(Instances.java:150)
	at com.jcabi.mysql.maven.plugin.Instances$1.run(Instances.java:137)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.jcabi.mysql.maven.plugin.Instances$AjcClosure3
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 3 more

```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@MHL3060 doesn't seem to be a big problem, but thanks for reporting it. We should probably get rid of the AOP entirely, in this plugin. Will do it soon.
